# input file


[show]
structure = true
isosurface = false
lattice = false
axis = false

[structure]
cube_header = "flpq/LPQ/LPQ.kinetic_energy_density.cube"
bond_factor = 1.6
bond_size_ratio = 1.0
atom_size_ratio = 0.5

color_atoms = true
color_bonds = false
color_bar_bond = false
color_name_bond = "blue_green_red"
colors_bond = ["#0000FF", "#00FFFF", "#00C600", "#FFFF00", "#FF0000"]
max_bond = 1.6
min_bond = 1.3

number = false
element = false

[isosurface]
### For surface plot ###
cube1 = "flpq/LPQ/LPQ.kinetic_energy_density.cube" 
### For surface color ###
cube2 = "flpq_ew/LPQ/LPQ.chemical_potential.cube"
isovalue = 0.00001
max_value = -0.2
min_value = -0.7
periodicity = [0,0,0] # 0:off, 1:on for boundary condition
### Color bar setting ###
color_bar = true
color_name = "blue_green_red"
colors = ["#0000FF", "#00FFFF", "#00C600", "#FFFF00", "#FF0000"]
alpha = 0.5
shade = false
smooth = true

[view]
roughness = 3
supercell = [1,1,1]
elev = -90
azim = 90
ratio_zoom = 1.0
project_type = "ortho"  # ortho / persp
centering = true
translate = [0.0, 0.0, 0.0]

[save]
interactive = true
output_name = "chempot"
pdf = false
obj = false
png = false
Plotly = false


#[builder]
#supercell = [1,1,1]
#pop = [] # list of atoms
#
#
#[builder.task1]
#task = true
#export = "INPUT.dat" # "out.cif"
#[builder.task1.group]
#atoms = [1,2] # list of atoms
#translate = [0.0, 0.0, 0.0]
##copy = [0.0, 0.0, 0.0]
#
#[builder.task1.group.rotate]
#center = [0.0, 0.0, 0.0]
#euler_angle = [0.0, 0.0] # phi, theta

